version: "3.7"

services:
  nest-api:
    image: nest_api
    build: .

    environment:
      SUPABASE_URL: "https://xqsvvjdxzbgpjoyyxzbn.supabase.co"
      SUPABASE_KEY: "sb_publishable_sDbbRSb8raWkuh1kNIRR-Q_Njv_kcIq"

    networks:
      - network_swarm_public

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_swarm_public"
        - "traefik.http.routers.nest.rule=Host(`autoanalytics.mundoevogard.com`)"
        - "traefik.http.routers.nest.entrypoints=websecure"
        - "traefik.http.routers.nest.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.nest.loadbalancer.server.port=3000"

networks:
  network_swarm_public:
    external: true